{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
-- This file was automatically generated by scripts/gen_html.py
module Alder.Html.Attributes
    ( key
    , accept
    , accessKey
    , action
    , allowFullScreen
    , allowTransparency
    , alt
    , async
    , autocomplete
    , autofocus
    , autoplay
    , cellPadding
    , cellSpacing
    , charset
    , checked
    , colSpan
    , cols
    , content
    , contentEditable
    , contextMenu
    , controls
    , data_
    , dateTime
    , defer
    , dir
    , disabled
    , download
    , draggable
    , encType
    , for
    , form
    , formNoValidate
    , frameBorder
    , height
    , hidden
    , href
    , htmlFor
    , icon
    , label
    , lang
    , list
    , loop
    , max
    , maxLength
    , method
    , min
    , multiple
    , name
    , noValidate
    , onBlur
    , onChange
    , onClick
    , onDoubleClick
    , onFocus
    , onInput
    , onKeyDown
    , onKeyPress
    , onKeyUp
    , onMouseDown
    , onMouseEnter
    , onMouseLeave
    , onMouseMove
    , onMouseUp
    , onSubmit
    , pattern
    , placeholder
    , poster
    , preload
    , radioGroup
    , readOnly
    , rel
    , required
    , reversed
    , role
    , rowSpan
    , rows
    , sandbox
    , scope
    , scrollLeft
    , scrollTop
    , seamless
    , selected
    , size
    , span
    , spellCheck
    , src
    , srcDoc
    , step
    , style
    , tabIndex
    , target
    , title
    , type_
    , value
    , width
    , wmode
    ) where

import           Data.Text           (Text)

import qualified Alder.Html.Events   as E
import           Alder.Html.Internal

-- | The @accept@ attribute.
accept :: Text -> Attribute
accept = attribute "accept"

-- | The @accesskey@ attribute.
accessKey :: Text -> Attribute
accessKey = attribute "accesskey"

-- | The @action@ attribute.
action :: Text -> Attribute
action = attribute "action"

-- | The @allowfullscreen@ attribute.
allowFullScreen :: Text -> Attribute
allowFullScreen = attribute "allowfullscreen"

-- | The @allowtransparency@ attribute.
allowTransparency :: Text -> Attribute
allowTransparency = attribute "allowtransparency"

-- | The @alt@ attribute.
alt :: Text -> Attribute
alt = attribute "alt"

-- | The @async@ attribute.
async :: Attribute
async = boolean "async"

-- | The @autocomplete@ attribute.
autocomplete :: Attribute
autocomplete = boolean "autocomplete"

-- | The @autofocus@ attribute.
autofocus :: Attribute
autofocus = boolean "autofocus"

-- | The @autoplay@ attribute.
autoplay :: Attribute
autoplay = boolean "autoplay"

-- | The @cellpadding@ attribute.
cellPadding :: Text -> Attribute
cellPadding = attribute "cellpadding"

-- | The @cellspacing@ attribute.
cellSpacing :: Text -> Attribute
cellSpacing = attribute "cellspacing"

-- | The @charset@ attribute.
charset :: Text -> Attribute
charset = attribute "charset"

-- | The @checked@ attribute.
checked :: Attribute
checked = boolean "checked"

-- | The @colspan@ attribute.
colSpan :: Text -> Attribute
colSpan = attribute "colspan"

-- | The @cols@ attribute.
cols :: Text -> Attribute
cols = attribute "cols"

-- | The @content@ attribute.
content :: Text -> Attribute
content = attribute "content"

-- | The @contenteditable@ attribute.
contentEditable :: Text -> Attribute
contentEditable = attribute "contenteditable"

-- | The @contextmenu@ attribute.
contextMenu :: Text -> Attribute
contextMenu = attribute "contextmenu"

-- | The @controls@ attribute.
controls :: Text -> Attribute
controls = attribute "controls"

-- | The @data@ attribute.
data_ :: Text -> Attribute
data_ = attribute "data"

-- | The @datetime@ attribute.
dateTime :: Text -> Attribute
dateTime = attribute "datetime"

-- | The @defer@ attribute.
defer :: Attribute
defer = boolean "defer"

-- | The @dir@ attribute.
dir :: Text -> Attribute
dir = attribute "dir"

-- | The @disabled@ attribute.
disabled :: Attribute
disabled = boolean "disabled"

-- | The @download@ attribute.
download :: Attribute
download = boolean "download"

-- | The @draggable@ attribute.
draggable :: Text -> Attribute
draggable = attribute "draggable"

-- | The @enctype@ attribute.
encType :: Text -> Attribute
encType = attribute "enctype"

-- | The @for@ attribute.
for :: Text -> Attribute
for = attribute "for"

-- | The @form@ attribute.
form :: Text -> Attribute
form = attribute "form"

-- | The @formnovalidate@ attribute.
formNoValidate :: Text -> Attribute
formNoValidate = attribute "formnovalidate"

-- | The @frameborder@ attribute.
frameBorder :: Text -> Attribute
frameBorder = attribute "frameborder"

-- | The @height@ attribute.
height :: Text -> Attribute
height = attribute "height"

-- | The @hidden@ attribute.
hidden :: Attribute
hidden = boolean "hidden"

-- | The @href@ attribute.
href :: Text -> Attribute
href = attribute "href"

-- | The @htmlfor@ attribute.
htmlFor :: Text -> Attribute
htmlFor = attribute "htmlfor"

-- | The @icon@ attribute.
icon :: Text -> Attribute
icon = attribute "icon"

-- | The @label@ attribute.
label :: Text -> Attribute
label = attribute "label"

-- | The @lang@ attribute.
lang :: Text -> Attribute
lang = attribute "lang"

-- | The @list@ attribute.
list :: Text -> Attribute
list = attribute "list"

-- | The @loop@ attribute.
loop :: Attribute
loop = boolean "loop"

-- | The @max@ attribute.
max :: Text -> Attribute
max = attribute "max"

-- | The @maxlength@ attribute.
maxLength :: Text -> Attribute
maxLength = attribute "maxlength"

-- | The @method@ attribute.
method :: Text -> Attribute
method = attribute "method"

-- | The @min@ attribute.
min :: Text -> Attribute
min = attribute "min"

-- | The @multiple@ attribute.
multiple :: Attribute
multiple = boolean "multiple"

-- | The @name@ attribute.
name :: Text -> Attribute
name = attribute "name"

-- | The @novalidate@ attribute.
noValidate :: Attribute
noValidate = boolean "novalidate"

-- | Set the handler for the @Blur@ event.
onBlur :: Handler f => f E.FocusEvent -> Attribute
onBlur = onEvent Blur

-- | Set the handler for the @Change@ event.
onChange :: Handler f => f E.InputEvent -> Attribute
onChange = onEvent Change

-- | Set the handler for the @Click@ event.
onClick :: Handler f => f E.MouseEvent -> Attribute
onClick = onEvent Click

-- | Set the handler for the @DoubleClick@ event.
onDoubleClick :: Handler f => f E.MouseEvent -> Attribute
onDoubleClick = onEvent DoubleClick

-- | Set the handler for the @Focus@ event.
onFocus :: Handler f => f E.FocusEvent -> Attribute
onFocus = onEvent Focus

-- | Set the handler for the @Input@ event.
onInput :: Handler f => f E.InputEvent -> Attribute
onInput = onEvent Input

-- | Set the handler for the @KeyDown@ event.
onKeyDown :: Handler f => f E.KeyboardEvent -> Attribute
onKeyDown = onEvent KeyDown

-- | Set the handler for the @KeyPress@ event.
onKeyPress :: Handler f => f E.KeyboardEvent -> Attribute
onKeyPress = onEvent KeyPress

-- | Set the handler for the @KeyUp@ event.
onKeyUp :: Handler f => f E.KeyboardEvent -> Attribute
onKeyUp = onEvent KeyUp

-- | Set the handler for the @MouseDown@ event.
onMouseDown :: Handler f => f E.MouseEvent -> Attribute
onMouseDown = onEvent MouseDown

-- | Set the handler for the @MouseEnter@ event.
onMouseEnter :: Handler f => f E.MouseEvent -> Attribute
onMouseEnter = onEvent MouseEnter

-- | Set the handler for the @MouseLeave@ event.
onMouseLeave :: Handler f => f E.MouseEvent -> Attribute
onMouseLeave = onEvent MouseLeave

-- | Set the handler for the @MouseMove@ event.
onMouseMove :: Handler f => f E.MouseEvent -> Attribute
onMouseMove = onEvent MouseMove

-- | Set the handler for the @MouseUp@ event.
onMouseUp :: Handler f => f E.MouseEvent -> Attribute
onMouseUp = onEvent MouseUp

-- | Set the handler for the @Submit@ event.
onSubmit :: Handler f => f E.SubmitEvent -> Attribute
onSubmit = onEvent Submit

-- | The @pattern@ attribute.
pattern :: Text -> Attribute
pattern = attribute "pattern"

-- | The @placeholder@ attribute.
placeholder :: Text -> Attribute
placeholder = attribute "placeholder"

-- | The @poster@ attribute.
poster :: Text -> Attribute
poster = attribute "poster"

-- | The @preload@ attribute.
preload :: Attribute
preload = boolean "preload"

-- | The @radiogroup@ attribute.
radioGroup :: Text -> Attribute
radioGroup = attribute "radiogroup"

-- | The @readonly@ attribute.
readOnly :: Attribute
readOnly = boolean "readonly"

-- | The @rel@ attribute.
rel :: Text -> Attribute
rel = attribute "rel"

-- | The @required@ attribute.
required :: Attribute
required = boolean "required"

-- | The @reversed@ attribute.
reversed :: Attribute
reversed = boolean "reversed"

-- | The @role@ attribute.
role :: Text -> Attribute
role = attribute "role"

-- | The @rowspan@ attribute.
rowSpan :: Text -> Attribute
rowSpan = attribute "rowspan"

-- | The @rows@ attribute.
rows :: Text -> Attribute
rows = attribute "rows"

-- | The @sandbox@ attribute.
sandbox :: Text -> Attribute
sandbox = attribute "sandbox"

-- | The @scope@ attribute.
scope :: Text -> Attribute
scope = attribute "scope"

-- | The @scrollleft@ attribute.
scrollLeft :: Text -> Attribute
scrollLeft = attribute "scrollleft"

-- | The @scrolltop@ attribute.
scrollTop :: Text -> Attribute
scrollTop = attribute "scrolltop"

-- | The @seamless@ attribute.
seamless :: Attribute
seamless = boolean "seamless"

-- | The @selected@ attribute.
selected :: Text -> Attribute
selected = attribute "selected"

-- | The @size@ attribute.
size :: Text -> Attribute
size = attribute "size"

-- | The @span@ attribute.
span :: Text -> Attribute
span = attribute "span"

-- | The @spellcheck@ attribute.
spellCheck :: Attribute
spellCheck = boolean "spellcheck"

-- | The @src@ attribute.
src :: Text -> Attribute
src = attribute "src"

-- | The @srcdoc@ attribute.
srcDoc :: Text -> Attribute
srcDoc = attribute "srcdoc"

-- | The @step@ attribute.
step :: Text -> Attribute
step = attribute "step"

-- | The @style@ attribute.
style :: Text -> Attribute
style = attribute "style"

-- | The @tabindex@ attribute.
tabIndex :: Text -> Attribute
tabIndex = attribute "tabindex"

-- | The @target@ attribute.
target :: Text -> Attribute
target = attribute "target"

-- | The @title@ attribute.
title :: Text -> Attribute
title = attribute "title"

-- | The @type@ attribute.
type_ :: Text -> Attribute
type_ = attribute "type"

-- | The @value@ attribute.
value :: Text -> Attribute
value = attribute "value"

-- | The @width@ attribute.
width :: Text -> Attribute
width = attribute "width"

-- | The @wmode@ attribute.
wmode :: Text -> Attribute
wmode = attribute "wmode"
