{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
-- This file was automatically generated by scripts/gen_html.py
module Alder.Html.Elements
    ( a
    , abbr
    , address
    , area
    , article
    , aside
    , audio
    , b
    , base
    , bdi
    , bdo
    , big
    , blockquote
    , body
    , br
    , button
    , canvas
    , caption
    , cite
    , code
    , col
    , colgroup
    , data_
    , datalist
    , dd
    , del
    , details
    , dfn
    , div
    , dl
    , dt
    , em
    , embed
    , fieldset
    , figcaption
    , figure
    , footer
    , form
    , h1
    , h2
    , h3
    , h4
    , h5
    , h6
    , head
    , header
    , hr
    , html
    , i
    , iframe
    , img
    , input
    , ins
    , kbd
    , keygen
    , label
    , legend
    , li
    , link
    , main
    , map
    , mark
    , menu
    , menuitem
    , meta
    , meter
    , nav
    , noscript
    , object
    , ol
    , optgroup
    , option
    , output
    , p
    , param
    , pre
    , progress
    , q
    , rp
    , rt
    , ruby
    , s
    , samp
    , script
    , section
    , select
    , small
    , source
    , span
    , strong
    , style
    , sub
    , summary
    , sup
    , table
    , tbody
    , td
    , textarea
    , tfoot
    , th
    , thead
    , time
    , title
    , tr
    , track
    , u
    , ul
    , var
    , video
    , wbr
    ) where

import           Alder.Html.Internal

-- | The HTML @a@ tag.
a :: Html -> Html
a = parent "a"

-- | The HTML @abbr@ tag.
abbr :: Html -> Html
abbr = parent "abbr"

-- | The HTML @address@ tag.
address :: Html -> Html
address = parent "address"

-- | The HTML @area@ tag.
area :: Html
area = leaf "area"

-- | The HTML @article@ tag.
article :: Html -> Html
article = parent "article"

-- | The HTML @aside@ tag.
aside :: Html -> Html
aside = parent "aside"

-- | The HTML @audio@ tag.
audio :: Html -> Html
audio = parent "audio"

-- | The HTML @b@ tag.
b :: Html -> Html
b = parent "b"

-- | The HTML @base@ tag.
base :: Html
base = leaf "base"

-- | The HTML @bdi@ tag.
bdi :: Html -> Html
bdi = parent "bdi"

-- | The HTML @bdo@ tag.
bdo :: Html -> Html
bdo = parent "bdo"

-- | The HTML @big@ tag.
big :: Html -> Html
big = parent "big"

-- | The HTML @blockquote@ tag.
blockquote :: Html -> Html
blockquote = parent "blockquote"

-- | The HTML @body@ tag.
body :: Html -> Html
body = parent "body"

-- | The HTML @br@ tag.
br :: Html
br = leaf "br"

-- | The HTML @button@ tag.
button :: Html -> Html
button = parent "button"

-- | The HTML @canvas@ tag.
canvas :: Html -> Html
canvas = parent "canvas"

-- | The HTML @caption@ tag.
caption :: Html -> Html
caption = parent "caption"

-- | The HTML @cite@ tag.
cite :: Html -> Html
cite = parent "cite"

-- | The HTML @code@ tag.
code :: Html -> Html
code = parent "code"

-- | The HTML @col@ tag.
col :: Html
col = leaf "col"

-- | The HTML @colgroup@ tag.
colgroup :: Html -> Html
colgroup = parent "colgroup"

-- | The HTML @data@ tag.
data_ :: Html -> Html
data_ = parent "data"

-- | The HTML @datalist@ tag.
datalist :: Html -> Html
datalist = parent "datalist"

-- | The HTML @dd@ tag.
dd :: Html -> Html
dd = parent "dd"

-- | The HTML @del@ tag.
del :: Html -> Html
del = parent "del"

-- | The HTML @details@ tag.
details :: Html -> Html
details = parent "details"

-- | The HTML @dfn@ tag.
dfn :: Html -> Html
dfn = parent "dfn"

-- | The HTML @div@ tag.
div :: Html -> Html
div = parent "div"

-- | The HTML @dl@ tag.
dl :: Html -> Html
dl = parent "dl"

-- | The HTML @dt@ tag.
dt :: Html -> Html
dt = parent "dt"

-- | The HTML @em@ tag.
em :: Html -> Html
em = parent "em"

-- | The HTML @embed@ tag.
embed :: Html
embed = leaf "embed"

-- | The HTML @fieldset@ tag.
fieldset :: Html -> Html
fieldset = parent "fieldset"

-- | The HTML @figcaption@ tag.
figcaption :: Html -> Html
figcaption = parent "figcaption"

-- | The HTML @figure@ tag.
figure :: Html -> Html
figure = parent "figure"

-- | The HTML @footer@ tag.
footer :: Html -> Html
footer = parent "footer"

-- | The HTML @form@ tag.
form :: Html -> Html
form = parent "form"

-- | The HTML @h1@ tag.
h1 :: Html -> Html
h1 = parent "h1"

-- | The HTML @h2@ tag.
h2 :: Html -> Html
h2 = parent "h2"

-- | The HTML @h3@ tag.
h3 :: Html -> Html
h3 = parent "h3"

-- | The HTML @h4@ tag.
h4 :: Html -> Html
h4 = parent "h4"

-- | The HTML @h5@ tag.
h5 :: Html -> Html
h5 = parent "h5"

-- | The HTML @h6@ tag.
h6 :: Html -> Html
h6 = parent "h6"

-- | The HTML @head@ tag.
head :: Html -> Html
head = parent "head"

-- | The HTML @header@ tag.
header :: Html -> Html
header = parent "header"

-- | The HTML @hr@ tag.
hr :: Html
hr = leaf "hr"

-- | The HTML @html@ tag.
html :: Html -> Html
html = parent "html"

-- | The HTML @i@ tag.
i :: Html -> Html
i = parent "i"

-- | The HTML @iframe@ tag.
iframe :: Html -> Html
iframe = parent "iframe"

-- | The HTML @img@ tag.
img :: Html
img = leaf "img"

-- | The HTML @input@ tag.
input :: Html
input = leaf "input"

-- | The HTML @ins@ tag.
ins :: Html -> Html
ins = parent "ins"

-- | The HTML @kbd@ tag.
kbd :: Html -> Html
kbd = parent "kbd"

-- | The HTML @keygen@ tag.
keygen :: Html
keygen = leaf "keygen"

-- | The HTML @label@ tag.
label :: Html -> Html
label = parent "label"

-- | The HTML @legend@ tag.
legend :: Html -> Html
legend = parent "legend"

-- | The HTML @li@ tag.
li :: Html -> Html
li = parent "li"

-- | The HTML @link@ tag.
link :: Html
link = leaf "link"

-- | The HTML @main@ tag.
main :: Html -> Html
main = parent "main"

-- | The HTML @map@ tag.
map :: Html -> Html
map = parent "map"

-- | The HTML @mark@ tag.
mark :: Html -> Html
mark = parent "mark"

-- | The HTML @menu@ tag.
menu :: Html -> Html
menu = parent "menu"

-- | The HTML @menuitem@ tag.
menuitem :: Html -> Html
menuitem = parent "menuitem"

-- | The HTML @meta@ tag.
meta :: Html
meta = leaf "meta"

-- | The HTML @meter@ tag.
meter :: Html -> Html
meter = parent "meter"

-- | The HTML @nav@ tag.
nav :: Html -> Html
nav = parent "nav"

-- | The HTML @noscript@ tag.
noscript :: Html -> Html
noscript = parent "noscript"

-- | The HTML @object@ tag.
object :: Html -> Html
object = parent "object"

-- | The HTML @ol@ tag.
ol :: Html -> Html
ol = parent "ol"

-- | The HTML @optgroup@ tag.
optgroup :: Html -> Html
optgroup = parent "optgroup"

-- | The HTML @option@ tag.
option :: Html -> Html
option = parent "option"

-- | The HTML @output@ tag.
output :: Html -> Html
output = parent "output"

-- | The HTML @p@ tag.
p :: Html -> Html
p = parent "p"

-- | The HTML @param@ tag.
param :: Html
param = leaf "param"

-- | The HTML @pre@ tag.
pre :: Html -> Html
pre = parent "pre"

-- | The HTML @progress@ tag.
progress :: Html -> Html
progress = parent "progress"

-- | The HTML @q@ tag.
q :: Html -> Html
q = parent "q"

-- | The HTML @rp@ tag.
rp :: Html -> Html
rp = parent "rp"

-- | The HTML @rt@ tag.
rt :: Html -> Html
rt = parent "rt"

-- | The HTML @ruby@ tag.
ruby :: Html -> Html
ruby = parent "ruby"

-- | The HTML @s@ tag.
s :: Html -> Html
s = parent "s"

-- | The HTML @samp@ tag.
samp :: Html -> Html
samp = parent "samp"

-- | The HTML @script@ tag.
script :: Html -> Html
script = parent "script"

-- | The HTML @section@ tag.
section :: Html -> Html
section = parent "section"

-- | The HTML @select@ tag.
select :: Html -> Html
select = parent "select"

-- | The HTML @small@ tag.
small :: Html -> Html
small = parent "small"

-- | The HTML @source@ tag.
source :: Html
source = leaf "source"

-- | The HTML @span@ tag.
span :: Html -> Html
span = parent "span"

-- | The HTML @strong@ tag.
strong :: Html -> Html
strong = parent "strong"

-- | The HTML @style@ tag.
style :: Html -> Html
style = parent "style"

-- | The HTML @sub@ tag.
sub :: Html -> Html
sub = parent "sub"

-- | The HTML @summary@ tag.
summary :: Html -> Html
summary = parent "summary"

-- | The HTML @sup@ tag.
sup :: Html -> Html
sup = parent "sup"

-- | The HTML @table@ tag.
table :: Html -> Html
table = parent "table"

-- | The HTML @tbody@ tag.
tbody :: Html -> Html
tbody = parent "tbody"

-- | The HTML @td@ tag.
td :: Html -> Html
td = parent "td"

-- | The HTML @textarea@ tag.
textarea :: Html -> Html
textarea = parent "textarea"

-- | The HTML @tfoot@ tag.
tfoot :: Html -> Html
tfoot = parent "tfoot"

-- | The HTML @th@ tag.
th :: Html -> Html
th = parent "th"

-- | The HTML @thead@ tag.
thead :: Html -> Html
thead = parent "thead"

-- | The HTML @time@ tag.
time :: Html -> Html
time = parent "time"

-- | The HTML @title@ tag.
title :: Html -> Html
title = parent "title"

-- | The HTML @tr@ tag.
tr :: Html -> Html
tr = parent "tr"

-- | The HTML @track@ tag.
track :: Html
track = leaf "track"

-- | The HTML @u@ tag.
u :: Html -> Html
u = parent "u"

-- | The HTML @ul@ tag.
ul :: Html -> Html
ul = parent "ul"

-- | The HTML @var@ tag.
var :: Html -> Html
var = parent "var"

-- | The HTML @video@ tag.
video :: Html -> Html
video = parent "video"

-- | The HTML @wbr@ tag.
wbr :: Html
wbr = leaf "wbr"
