{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
module Alder.Html.Elements where

import           Alder.Html.Internal

-- This file was automatically generated by scripts/gen_html.py

-- | The HTML @a@ tag.
a :: Html
a = Leaf "a"

-- | The HTML @abbr@ tag.
abbr :: Html
abbr = Leaf "abbr"

-- | The HTML @address@ tag.
address :: Html
address = Leaf "address"

-- | The HTML @area@ tag.
area :: Html -> Html
area = Parent "area"

-- | The HTML @article@ tag.
article :: Html
article = Leaf "article"

-- | The HTML @aside@ tag.
aside :: Html
aside = Leaf "aside"

-- | The HTML @audio@ tag.
audio :: Html
audio = Leaf "audio"

-- | The HTML @b@ tag.
b :: Html
b = Leaf "b"

-- | The HTML @base@ tag.
base :: Html -> Html
base = Parent "base"

-- | The HTML @bdi@ tag.
bdi :: Html
bdi = Leaf "bdi"

-- | The HTML @bdo@ tag.
bdo :: Html
bdo = Leaf "bdo"

-- | The HTML @big@ tag.
big :: Html
big = Leaf "big"

-- | The HTML @blockquote@ tag.
blockquote :: Html
blockquote = Leaf "blockquote"

-- | The HTML @body@ tag.
body :: Html
body = Leaf "body"

-- | The HTML @br@ tag.
br :: Html -> Html
br = Parent "br"

-- | The HTML @button@ tag.
button :: Html
button = Leaf "button"

-- | The HTML @canvas@ tag.
canvas :: Html
canvas = Leaf "canvas"

-- | The HTML @caption@ tag.
caption :: Html
caption = Leaf "caption"

-- | The HTML @cite@ tag.
cite :: Html
cite = Leaf "cite"

-- | The HTML @code@ tag.
code :: Html
code = Leaf "code"

-- | The HTML @col@ tag.
col :: Html -> Html
col = Parent "col"

-- | The HTML @colgroup@ tag.
colgroup :: Html
colgroup = Leaf "colgroup"

-- | The HTML @data@ tag.
data_ :: Html
data_ = Leaf "data"

-- | The HTML @datalist@ tag.
datalist :: Html
datalist = Leaf "datalist"

-- | The HTML @dd@ tag.
dd :: Html
dd = Leaf "dd"

-- | The HTML @del@ tag.
del :: Html
del = Leaf "del"

-- | The HTML @details@ tag.
details :: Html
details = Leaf "details"

-- | The HTML @dfn@ tag.
dfn :: Html
dfn = Leaf "dfn"

-- | The HTML @div@ tag.
div :: Html
div = Leaf "div"

-- | The HTML @dl@ tag.
dl :: Html
dl = Leaf "dl"

-- | The HTML @dt@ tag.
dt :: Html
dt = Leaf "dt"

-- | The HTML @em@ tag.
em :: Html
em = Leaf "em"

-- | The HTML @embed@ tag.
embed :: Html -> Html
embed = Parent "embed"

-- | The HTML @fieldset@ tag.
fieldset :: Html
fieldset = Leaf "fieldset"

-- | The HTML @figcaption@ tag.
figcaption :: Html
figcaption = Leaf "figcaption"

-- | The HTML @figure@ tag.
figure :: Html
figure = Leaf "figure"

-- | The HTML @footer@ tag.
footer :: Html
footer = Leaf "footer"

-- | The HTML @form@ tag.
form :: Html
form = Leaf "form"

-- | The HTML @h1@ tag.
h1 :: Html
h1 = Leaf "h1"

-- | The HTML @h2@ tag.
h2 :: Html
h2 = Leaf "h2"

-- | The HTML @h3@ tag.
h3 :: Html
h3 = Leaf "h3"

-- | The HTML @h4@ tag.
h4 :: Html
h4 = Leaf "h4"

-- | The HTML @h5@ tag.
h5 :: Html
h5 = Leaf "h5"

-- | The HTML @h6@ tag.
h6 :: Html
h6 = Leaf "h6"

-- | The HTML @head@ tag.
head :: Html
head = Leaf "head"

-- | The HTML @header@ tag.
header :: Html
header = Leaf "header"

-- | The HTML @hr@ tag.
hr :: Html -> Html
hr = Parent "hr"

-- | The HTML @html@ tag.
html :: Html
html = Leaf "html"

-- | The HTML @i@ tag.
i :: Html
i = Leaf "i"

-- | The HTML @iframe@ tag.
iframe :: Html
iframe = Leaf "iframe"

-- | The HTML @img@ tag.
img :: Html -> Html
img = Parent "img"

-- | The HTML @input@ tag.
input :: Html -> Html
input = Parent "input"

-- | The HTML @ins@ tag.
ins :: Html
ins = Leaf "ins"

-- | The HTML @kbd@ tag.
kbd :: Html
kbd = Leaf "kbd"

-- | The HTML @keygen@ tag.
keygen :: Html -> Html
keygen = Parent "keygen"

-- | The HTML @label@ tag.
label :: Html
label = Leaf "label"

-- | The HTML @legend@ tag.
legend :: Html
legend = Leaf "legend"

-- | The HTML @li@ tag.
li :: Html
li = Leaf "li"

-- | The HTML @link@ tag.
link :: Html -> Html
link = Parent "link"

-- | The HTML @main@ tag.
main :: Html
main = Leaf "main"

-- | The HTML @map@ tag.
map :: Html
map = Leaf "map"

-- | The HTML @mark@ tag.
mark :: Html
mark = Leaf "mark"

-- | The HTML @menu@ tag.
menu :: Html
menu = Leaf "menu"

-- | The HTML @menuitem@ tag.
menuitem :: Html
menuitem = Leaf "menuitem"

-- | The HTML @meta@ tag.
meta :: Html -> Html
meta = Parent "meta"

-- | The HTML @meter@ tag.
meter :: Html
meter = Leaf "meter"

-- | The HTML @nav@ tag.
nav :: Html
nav = Leaf "nav"

-- | The HTML @noscript@ tag.
noscript :: Html
noscript = Leaf "noscript"

-- | The HTML @object@ tag.
object :: Html
object = Leaf "object"

-- | The HTML @ol@ tag.
ol :: Html
ol = Leaf "ol"

-- | The HTML @optgroup@ tag.
optgroup :: Html
optgroup = Leaf "optgroup"

-- | The HTML @option@ tag.
option :: Html
option = Leaf "option"

-- | The HTML @output@ tag.
output :: Html
output = Leaf "output"

-- | The HTML @p@ tag.
p :: Html
p = Leaf "p"

-- | The HTML @param@ tag.
param :: Html -> Html
param = Parent "param"

-- | The HTML @pre@ tag.
pre :: Html
pre = Leaf "pre"

-- | The HTML @progress@ tag.
progress :: Html
progress = Leaf "progress"

-- | The HTML @q@ tag.
q :: Html
q = Leaf "q"

-- | The HTML @rp@ tag.
rp :: Html
rp = Leaf "rp"

-- | The HTML @rt@ tag.
rt :: Html
rt = Leaf "rt"

-- | The HTML @ruby@ tag.
ruby :: Html
ruby = Leaf "ruby"

-- | The HTML @s@ tag.
s :: Html
s = Leaf "s"

-- | The HTML @samp@ tag.
samp :: Html
samp = Leaf "samp"

-- | The HTML @script@ tag.
script :: Html
script = Leaf "script"

-- | The HTML @section@ tag.
section :: Html
section = Leaf "section"

-- | The HTML @select@ tag.
select :: Html
select = Leaf "select"

-- | The HTML @small@ tag.
small :: Html
small = Leaf "small"

-- | The HTML @source@ tag.
source :: Html -> Html
source = Parent "source"

-- | The HTML @span@ tag.
span :: Html
span = Leaf "span"

-- | The HTML @strong@ tag.
strong :: Html
strong = Leaf "strong"

-- | The HTML @style@ tag.
style :: Html
style = Leaf "style"

-- | The HTML @sub@ tag.
sub :: Html
sub = Leaf "sub"

-- | The HTML @summary@ tag.
summary :: Html
summary = Leaf "summary"

-- | The HTML @sup@ tag.
sup :: Html
sup = Leaf "sup"

-- | The HTML @table@ tag.
table :: Html
table = Leaf "table"

-- | The HTML @tbody@ tag.
tbody :: Html
tbody = Leaf "tbody"

-- | The HTML @td@ tag.
td :: Html
td = Leaf "td"

-- | The HTML @textarea@ tag.
textarea :: Html
textarea = Leaf "textarea"

-- | The HTML @tfoot@ tag.
tfoot :: Html
tfoot = Leaf "tfoot"

-- | The HTML @th@ tag.
th :: Html
th = Leaf "th"

-- | The HTML @thead@ tag.
thead :: Html
thead = Leaf "thead"

-- | The HTML @time@ tag.
time :: Html
time = Leaf "time"

-- | The HTML @title@ tag.
title :: Html
title = Leaf "title"

-- | The HTML @tr@ tag.
tr :: Html
tr = Leaf "tr"

-- | The HTML @track@ tag.
track :: Html -> Html
track = Parent "track"

-- | The HTML @u@ tag.
u :: Html
u = Leaf "u"

-- | The HTML @ul@ tag.
ul :: Html
ul = Leaf "ul"

-- | The HTML @var@ tag.
var :: Html
var = Leaf "var"

-- | The HTML @video@ tag.
video :: Html
video = Leaf "video"

-- | The HTML @wbr@ tag.
wbr :: Html -> Html
wbr = Parent "wbr"
