{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
module Alder.Html.Elements where

import           Alder.Html.Internal

-- This file was automatically generated by scripts/gen_html.py

-- | The HTML @a@ tag.
a :: Html -> Html
a = Parent "a"

-- | The HTML @abbr@ tag.
abbr :: Html -> Html
abbr = Parent "abbr"

-- | The HTML @address@ tag.
address :: Html -> Html
address = Parent "address"

-- | The HTML @area@ tag.
area :: Html
area = Leaf "area"

-- | The HTML @article@ tag.
article :: Html -> Html
article = Parent "article"

-- | The HTML @aside@ tag.
aside :: Html -> Html
aside = Parent "aside"

-- | The HTML @audio@ tag.
audio :: Html -> Html
audio = Parent "audio"

-- | The HTML @b@ tag.
b :: Html -> Html
b = Parent "b"

-- | The HTML @base@ tag.
base :: Html
base = Leaf "base"

-- | The HTML @bdi@ tag.
bdi :: Html -> Html
bdi = Parent "bdi"

-- | The HTML @bdo@ tag.
bdo :: Html -> Html
bdo = Parent "bdo"

-- | The HTML @big@ tag.
big :: Html -> Html
big = Parent "big"

-- | The HTML @blockquote@ tag.
blockquote :: Html -> Html
blockquote = Parent "blockquote"

-- | The HTML @body@ tag.
body :: Html -> Html
body = Parent "body"

-- | The HTML @br@ tag.
br :: Html
br = Leaf "br"

-- | The HTML @button@ tag.
button :: Html -> Html
button = Parent "button"

-- | The HTML @canvas@ tag.
canvas :: Html -> Html
canvas = Parent "canvas"

-- | The HTML @caption@ tag.
caption :: Html -> Html
caption = Parent "caption"

-- | The HTML @cite@ tag.
cite :: Html -> Html
cite = Parent "cite"

-- | The HTML @code@ tag.
code :: Html -> Html
code = Parent "code"

-- | The HTML @col@ tag.
col :: Html
col = Leaf "col"

-- | The HTML @colgroup@ tag.
colgroup :: Html -> Html
colgroup = Parent "colgroup"

-- | The HTML @data@ tag.
data_ :: Html -> Html
data_ = Parent "data"

-- | The HTML @datalist@ tag.
datalist :: Html -> Html
datalist = Parent "datalist"

-- | The HTML @dd@ tag.
dd :: Html -> Html
dd = Parent "dd"

-- | The HTML @del@ tag.
del :: Html -> Html
del = Parent "del"

-- | The HTML @details@ tag.
details :: Html -> Html
details = Parent "details"

-- | The HTML @dfn@ tag.
dfn :: Html -> Html
dfn = Parent "dfn"

-- | The HTML @div@ tag.
div :: Html -> Html
div = Parent "div"

-- | The HTML @dl@ tag.
dl :: Html -> Html
dl = Parent "dl"

-- | The HTML @dt@ tag.
dt :: Html -> Html
dt = Parent "dt"

-- | The HTML @em@ tag.
em :: Html -> Html
em = Parent "em"

-- | The HTML @embed@ tag.
embed :: Html
embed = Leaf "embed"

-- | The HTML @fieldset@ tag.
fieldset :: Html -> Html
fieldset = Parent "fieldset"

-- | The HTML @figcaption@ tag.
figcaption :: Html -> Html
figcaption = Parent "figcaption"

-- | The HTML @figure@ tag.
figure :: Html -> Html
figure = Parent "figure"

-- | The HTML @footer@ tag.
footer :: Html -> Html
footer = Parent "footer"

-- | The HTML @form@ tag.
form :: Html -> Html
form = Parent "form"

-- | The HTML @h1@ tag.
h1 :: Html -> Html
h1 = Parent "h1"

-- | The HTML @h2@ tag.
h2 :: Html -> Html
h2 = Parent "h2"

-- | The HTML @h3@ tag.
h3 :: Html -> Html
h3 = Parent "h3"

-- | The HTML @h4@ tag.
h4 :: Html -> Html
h4 = Parent "h4"

-- | The HTML @h5@ tag.
h5 :: Html -> Html
h5 = Parent "h5"

-- | The HTML @h6@ tag.
h6 :: Html -> Html
h6 = Parent "h6"

-- | The HTML @head@ tag.
head :: Html -> Html
head = Parent "head"

-- | The HTML @header@ tag.
header :: Html -> Html
header = Parent "header"

-- | The HTML @hr@ tag.
hr :: Html
hr = Leaf "hr"

-- | The HTML @html@ tag.
html :: Html -> Html
html = Parent "html"

-- | The HTML @i@ tag.
i :: Html -> Html
i = Parent "i"

-- | The HTML @iframe@ tag.
iframe :: Html -> Html
iframe = Parent "iframe"

-- | The HTML @img@ tag.
img :: Html
img = Leaf "img"

-- | The HTML @input@ tag.
input :: Html
input = Leaf "input"

-- | The HTML @ins@ tag.
ins :: Html -> Html
ins = Parent "ins"

-- | The HTML @kbd@ tag.
kbd :: Html -> Html
kbd = Parent "kbd"

-- | The HTML @keygen@ tag.
keygen :: Html
keygen = Leaf "keygen"

-- | The HTML @label@ tag.
label :: Html -> Html
label = Parent "label"

-- | The HTML @legend@ tag.
legend :: Html -> Html
legend = Parent "legend"

-- | The HTML @li@ tag.
li :: Html -> Html
li = Parent "li"

-- | The HTML @link@ tag.
link :: Html
link = Leaf "link"

-- | The HTML @main@ tag.
main :: Html -> Html
main = Parent "main"

-- | The HTML @map@ tag.
map :: Html -> Html
map = Parent "map"

-- | The HTML @mark@ tag.
mark :: Html -> Html
mark = Parent "mark"

-- | The HTML @menu@ tag.
menu :: Html -> Html
menu = Parent "menu"

-- | The HTML @menuitem@ tag.
menuitem :: Html -> Html
menuitem = Parent "menuitem"

-- | The HTML @meta@ tag.
meta :: Html
meta = Leaf "meta"

-- | The HTML @meter@ tag.
meter :: Html -> Html
meter = Parent "meter"

-- | The HTML @nav@ tag.
nav :: Html -> Html
nav = Parent "nav"

-- | The HTML @noscript@ tag.
noscript :: Html -> Html
noscript = Parent "noscript"

-- | The HTML @object@ tag.
object :: Html -> Html
object = Parent "object"

-- | The HTML @ol@ tag.
ol :: Html -> Html
ol = Parent "ol"

-- | The HTML @optgroup@ tag.
optgroup :: Html -> Html
optgroup = Parent "optgroup"

-- | The HTML @option@ tag.
option :: Html -> Html
option = Parent "option"

-- | The HTML @output@ tag.
output :: Html -> Html
output = Parent "output"

-- | The HTML @p@ tag.
p :: Html -> Html
p = Parent "p"

-- | The HTML @param@ tag.
param :: Html
param = Leaf "param"

-- | The HTML @pre@ tag.
pre :: Html -> Html
pre = Parent "pre"

-- | The HTML @progress@ tag.
progress :: Html -> Html
progress = Parent "progress"

-- | The HTML @q@ tag.
q :: Html -> Html
q = Parent "q"

-- | The HTML @rp@ tag.
rp :: Html -> Html
rp = Parent "rp"

-- | The HTML @rt@ tag.
rt :: Html -> Html
rt = Parent "rt"

-- | The HTML @ruby@ tag.
ruby :: Html -> Html
ruby = Parent "ruby"

-- | The HTML @s@ tag.
s :: Html -> Html
s = Parent "s"

-- | The HTML @samp@ tag.
samp :: Html -> Html
samp = Parent "samp"

-- | The HTML @script@ tag.
script :: Html -> Html
script = Parent "script"

-- | The HTML @section@ tag.
section :: Html -> Html
section = Parent "section"

-- | The HTML @select@ tag.
select :: Html -> Html
select = Parent "select"

-- | The HTML @small@ tag.
small :: Html -> Html
small = Parent "small"

-- | The HTML @source@ tag.
source :: Html
source = Leaf "source"

-- | The HTML @span@ tag.
span :: Html -> Html
span = Parent "span"

-- | The HTML @strong@ tag.
strong :: Html -> Html
strong = Parent "strong"

-- | The HTML @style@ tag.
style :: Html -> Html
style = Parent "style"

-- | The HTML @sub@ tag.
sub :: Html -> Html
sub = Parent "sub"

-- | The HTML @summary@ tag.
summary :: Html -> Html
summary = Parent "summary"

-- | The HTML @sup@ tag.
sup :: Html -> Html
sup = Parent "sup"

-- | The HTML @table@ tag.
table :: Html -> Html
table = Parent "table"

-- | The HTML @tbody@ tag.
tbody :: Html -> Html
tbody = Parent "tbody"

-- | The HTML @td@ tag.
td :: Html -> Html
td = Parent "td"

-- | The HTML @textarea@ tag.
textarea :: Html -> Html
textarea = Parent "textarea"

-- | The HTML @tfoot@ tag.
tfoot :: Html -> Html
tfoot = Parent "tfoot"

-- | The HTML @th@ tag.
th :: Html -> Html
th = Parent "th"

-- | The HTML @thead@ tag.
thead :: Html -> Html
thead = Parent "thead"

-- | The HTML @time@ tag.
time :: Html -> Html
time = Parent "time"

-- | The HTML @title@ tag.
title :: Html -> Html
title = Parent "title"

-- | The HTML @tr@ tag.
tr :: Html -> Html
tr = Parent "tr"

-- | The HTML @track@ tag.
track :: Html
track = Leaf "track"

-- | The HTML @u@ tag.
u :: Html -> Html
u = Parent "u"

-- | The HTML @ul@ tag.
ul :: Html -> Html
ul = Parent "ul"

-- | The HTML @var@ tag.
var :: Html -> Html
var = Parent "var"

-- | The HTML @video@ tag.
video :: Html -> Html
video = Parent "video"

-- | The HTML @wbr@ tag.
wbr :: Html
wbr = Leaf "wbr"
